/**
 * Banco de ideas de contenido de locodea. (28-9-2026).
 *
 * Solo para Jesús y Alejandro. Cada idea sale de un desarrollo que ya está en
 * la carpeta de locodea. (Code Apps, Power Pages, Power BI) o de un flujo o
 * agente que tiene sentido construir encima, y se apoya en lo que tiene tirada
 * ahora en YouTube y LinkedIn (cifras en REF, vistas el 27–28 de septiembre de 2026).
 *
 * Lo usan contenido-ideas.mjs (carga en Dataverse) y el documento
 * «04 - Marketing/Contenidos/Banco de ideas de contenido.md».
 */

/** Referencias de lo que funciona ahora. Visualizaciones de YouTube y reacciones de LinkedIn. */
export const REF = {
  excelApp: 'Reza Dorrani, «Cómo convertir hojas de Excel en Power Apps»: 283.000 visualizaciones; su versión con agentes de programación lleva 83.000 en 3 semanas',
  workflows: 'Collaboration Simplified, «El nuevo agente de flujos de trabajo de Copilot»: 724.000; «NEW Microsoft Workflows…»: 189.000 en 4 semanas',
  agenteM365: 'Teacher\'s Tech, «Cómo crear un agente de IA con Microsoft 365 Copilot»: 439.000',
  agenteES: 'Xavier Mitjana, «Crea tu primer agente de IA en 15 minutos (sin programar)»: 249.000 en 8 días, en español',
  claudePBI: 'Mike Dion, «Claude Just Replaced My Power BI Developer»: 292.000; Power BI Bro, «Claude + Power BI con MCP»: 225.000; «Dashboard en 3 minutos con Claude»: 930.000',
  claudeCode: 'Benjamín Cordero, «Claude Code: curso completo en español»: 852.000 en un mes; Nate Gentile, «La IA es mi nuevo empleado | Claude Code»: 919.000',
  jesusCanal: 'Canal de Jesús: «Proyecto completo de Power BI con Claude» 6.200 y «Skills de Microsoft con Claude» 2.700, lo mejor del canal; el del agente con Business Central se quedó en 38 por un título que describía la tecnología',
  reportSkills: 'Guy in a Cube, «Power BI Report Skills»: 144.000',
  fabricApps: 'How to Power BI, «Adiós a los reportes de Power BI: Fabric Apps»: 166.000',
  facturasIA: 'DamoBird365, «Este flujo de Power Automate lee facturas con IA»: 26.000; Officefacil, «Esta automatización parece ilegal: elimina horas de trabajo»: 50.000 en 2 semanas, en español',
  codeApps: 'Reza Dorrani, «Tutorial completo de Power Apps Code Apps»: 69.000; «Servidor MCP de Power Apps»: 51.000; su post de vibe coding con code apps: 694 reacciones en LinkedIn',
  cowork: 'Reza Dorrani, «Copilot Cowork ya puede crear aplicaciones reales»: 39.000 en 2 semanas; «GPT-6 Astra Built My Power App in 20 Minutes»: 27.000 en 2 semanas',
  m365malUso: 'Bulb Digital, «Microsoft 365 es frustrante porque lo estás usando mal»: 23.000 en 10 días',
  tipsDiseno: 'Laura Rogers, «10 Power Apps Tips to Instantly Level Up Your Skills»: 95.000; «Grid controls»: 41.000 en 2 semanas',
  pbiDiseno: 'Leila Gharani, «Power BI Card Visuals»: 102.000; Vedakarna, «Panel de RR. HH. en Power BI»: 181.000',
  licencias: 'Jukka Niiranen, «RIP premium apps at $5/mo» (fin de la licencia por app): 318 reacciones y 105 comentarios en LinkedIn. Los posts de dinero y licencias con opinión son los que más debate generan en el nicho',
  construidoYo: 'Nate Herk, «I built an AI agent that builds n8n workflows»: 837 reacciones en LinkedIn; Scott Durow, app de Gantt con Code Apps: 165. El patrón «lo he construido yo» con demo visual es el que mejor funciona',
  agenteFlujo: 'Adi Leibowitz, «Llamar a agentes desde Power Automate y esperar la respuesta»: 611 reacciones en LinkedIn',
  agenteLicencias: 'Kristine Kolodziejski, agente propio que responde dudas de licencias de Power Platform: 572 reacciones',
  bcAgente: 'Søren Friis Alexandersen, «Payables Agent en Business Central»: 250 reacciones, lo que más funciona de Business Central en LinkedIn; los vídeos oficiales de BC rondan 4.000–9.000',
  produccionHueco: 'Lo más visto de «Power Apps producción» tiene 4–6 años («PowerApps. Control de producción»: 10.000). Nadie lo enseña con 3D y tablet moderna',
  nichoES: 'En español, los posts de Power Platform y Business Central se quedan en 5–30 reacciones: casi todo son enlaces a blogs y anuncios. Con demos, cifras y opinión se destaca rápido',
  datosPropios: 'Los posts de «he analizado X» con datos propios son de los que más se guardan y comparten en LinkedIn (Chris Donnelly, Amanda Natividad)',
  normativa: 'Contenido con fecha legal real: urgencia verdadera para la empresa. Nadie lo explica con la app hecha',
  webinar: 'Asiste en torno al 44 % de los inscritos (GoTo); con demo en directo es la pieza que más convierte en reuniones',
}

/** Series: cómo se organiza el banco. */
export const SERIES = [
  ['Una app en 60 segundos', 'Un vídeo vertical por desarrollo: el resultado en el segundo 0 y la app funcionando. Lo graba y monta Alejandro.'],
  ['Construido con IA', 'Cómo construimos con Claude Code y nuestras skills: la línea que mejor le funciona al canal de Jesús.'],
  ['Power BI con IA', 'Paneles del catálogo, gráficos en DAX con SVG y Power BI construido con IA.'],
  ['Automatiza esto', 'Flujos de Power Automate que conectan nuestras apps. La mayoría hay que construirlos: cada flujo es un vídeo.'],
  ['Agentes de IA con Microsoft', 'Agentes de Copilot Studio sobre los datos de nuestras apps.'],
  ['Business Central + Power Platform', 'Complementa lo que ya tenéis apuntado de Business Central: agentes, Power BI y extensiones.'],
  ['Normativa que llega', 'Obligaciones con fecha y la app que las resuelve.'],
  ['Diseño que se usa', 'Por qué nuestras apps no parecen de Power Apps: sistema de diseño, UX de planta, 3D.'],
  ['He analizado…', 'Datos propios de los análisis de mercado que hay en la carpeta docs de cada app.'],
  ['Detrás de locodea.', 'Construir en público: cómo trabajamos, cómo publicamos, lo que cuesta.'],
  ['Power Pages: portales para tus clientes', 'Portales de cliente y de proveedor con Power Pages como sitio de código (React).'],
  ['Webinars y directos', 'Eventos de 45 minutos con demo en directo. Los hacen Jesús y Alejandro juntos.'],
]

const J = 'jesus', A = 'alejandro'
const CA = 'codeapps', PBI = 'powerbi', PP = 'powerpages'

/**
 * Cada idea: t título · r responsable · c canal · f formato · s serie · tec tecnologías · o desarrollo de origen
 * p proyecto (cartera) · g gancho · e qué se enseña · est estructura · d duración · x por qué puede funcionar (texto o clave de REF)
 * pre qué hay que preparar
 */
export const IDEAS = [
  // ───────────────────────── Una app en 60 segundos
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'La fábrica en una tablet: instrucciones de montaje en 3D',
    tec: 'Power Apps (Code App), React, Three.js, Dataverse', o: 'Code App · Producción',
    g: '«Así aprende a montar una pieza alguien que entra hoy en planta.»',
    e: 'El operario toca su nombre, abre su orden, gira la bomba en 3D, la separa en piezas y sigue los pasos; al fondo, el plano de la fábrica en vivo.',
    est: ['0–3 s: la pieza en 3D separándose en la tablet', '3–20 s: fichar en la orden y sumar unidades', '20–45 s: instrucciones paso a paso', '45–60 s: el responsable ve la planta en vivo'],
    d: '45–60 s vertical, subtítulos quemados. Publicar también en Shorts y Reels.', x: 'produccionHueco',
    pre: 'Grabación de pantalla limpia de la demo en tablet (datos de demostración).' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Tu almacén en 3D: la ruta más corta del preparador',
    tec: 'Power Apps (Code App), React, Three.js, Dataverse', o: 'Code App · Almacén',
    g: '«Tu almacén no tiene un problema de espacio. Tiene un problema de "nadie sabe dónde está nada".»',
    e: 'El mapa 3D del almacén, la ruta del preparador pasillo a pasillo, el escaneo y el recuento cíclico.',
    est: ['Gancho sobre el mapa 3D girando', 'Pedido → ruta dibujada en el mapa', 'Escaneo y lote con caducidad (FEFO)', 'Cierre: inventario sin parar el almacén'],
    d: '45 s vertical.', x: 'construidoYo', pre: 'Grabar el mapa 3D a 60 fps para que el giro sea suave.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: '¿Quién tiene cada portátil? El inventario informático en un mapa 3D',
    tec: 'Power Apps (Code App), Three.js, Dataverse, PowerShell', o: 'Code App · Parque',
    g: '«¿Sabes cuántos portátiles tiene tu empresa y quién tiene cada uno?»',
    e: 'El mapa 3D de la oficina con cada equipo, la ficha del portátil, el acta firmada con el dedo y el script que lo inventaría solo.',
    est: ['Pregunta a cámara (Alejandro)', 'Mapa 3D de la sede', 'Entrega de un portátil con firma en la pantalla', 'Script de PowerShell que da de alta los equipos'],
    d: '50 s vertical.', x: 'construidoYo', pre: 'Demo con Almenara Logística (datos de ejemplo).' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Del pedido al pago: el portal del proveedor en 60 segundos',
    tec: 'Power Apps (Code App), Dataverse, Power Automate', o: 'Code App · Compras',
    g: '«Tu proveedor confirma el pedido él solo. Tú ya no llamas.»',
    e: 'Solicitud → pedido → el proveedor confirma en su portal → recepción → la factura cuadra con pedido y albarán.',
    est: ['Resultado primero: la factura cuadrada en verde', 'Rebobinar al pedido', 'Portal del proveedor', 'Recepción con incidencia (fresas dañadas)'],
    d: '60 s vertical.', x: 'construidoYo', pre: 'Demo de Mecanizados Arlanza.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Fichar en una tablet y que el registro de jornada se haga solo',
    tec: 'Power Apps (Code App), Dataverse', o: 'Code App · Jornada',
    g: '«El registro de jornada, dentro del Microsoft 365 que ya usa tu empresa. Y con tu logo.»',
    e: 'Terminal de fichaje en tablet, vacaciones, turnos y el cambio de marca blanca (logo y color) en directo.',
    est: ['Fichaje en la tablet', 'Vacaciones aprobadas', 'Cambio de logo y color en 5 segundos', 'Exportación del registro'],
    d: '45 s vertical.', x: 'construidoYo', pre: 'Preparar dos marcas de ejemplo para el cambio de marca blanca.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Cursos internos con certificado y el registro ISO 9001 que se hace solo',
    tec: 'Power Apps (Code App), Dataverse, SharePoint, Microsoft Stream', o: 'Code App · Formación',
    g: '«El registro de formación que te pide el auditor, generado solo.»',
    e: 'Un curso con vídeo y cuestionario, el certificado al terminar y el panel del responsable con quién va al día.',
    est: ['Certificado apareciendo (resultado)', 'Curso por módulos', 'Panel del responsable', 'Exportación del registro ISO 9001 (7.2)'],
    d: '50 s vertical.', x: 'construidoYo', pre: 'Curso de ejemplo con vídeo propio.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Un CRM con tu marca, dentro de tu Microsoft 365',
    tec: 'Power Apps (Code App), Dataverse, Outlook', o: 'Code App · CRM',
    g: '«De la primera llamada al cobro, en una sola app que es tuya.»',
    e: 'Embudo de oportunidades, oferta, pedido y factura como documento de trabajo, con el correo de Outlook dentro.',
    est: ['Embudo arrastrando una oportunidad a «Ganada»', 'Oferta generada', 'Pedido y factura', 'Marca blanca'],
    d: '60 s vertical. Complementa la idea que ya tenéis de comparar con CRM caros.', x: 'construidoYo', pre: 'Datos de demo del CRM.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Gestión de proyectos sin las quejas de Asana y Monday',
    tec: 'Power Apps (Code App), Dataverse', o: 'Code App · Proyectos',
    g: '«Lo mejor de Planner, Asana y Monday. Sin sus quejas más repetidas.»',
    e: 'Vista de proyecto, tareas, cambio de rol «Ver la app como…» y el invitado externo.',
    est: ['Tablero moviéndose', 'Cambio de rol en directo', 'Invitado externo con permisos limitados'],
    d: '45 s vertical. Va de la mano de «He comparado 9 herramientas de proyectos».', x: 'construidoYo', pre: 'Demo Alcora Ingeniería.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Marca el golpe tocando la furgoneta en 3D',
    tec: 'Power Apps (Code App), Three.js, Dataverse', o: 'Code App · Inspección',
    g: '«Antes: fotos sueltas por WhatsApp y un parte en papel. Ahora: un toque.»',
    e: 'Checklist por tipo de vehículo, daño marcado sobre el modelo 3D, firma y el informe al momento.',
    est: ['Toque en el 3D y aparece el daño', 'Checklist rápido', 'Firma', 'Informe emitido'],
    d: '40 s vertical.', x: 'construidoYo', pre: 'Grabar en tablet real, en exterior si es posible.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: PP, t: 'El DeCA desde el móvil del conductor: QR listo para la Guardia Civil',
    tec: 'Power Pages (sitio de código, React), Dataverse', o: 'Power Pages · DeCA',
    g: '«Desde el 5 de octubre el papel ya no vale en el transporte.»',
    e: 'El conductor elige matrícula, hace foto y firma en carga y entrega, y enseña el QR.',
    est: ['QR en pantalla (resultado)', 'Alta del transporte en cuatro preguntas', 'Carga y entrega con foto y firma', 'Pantalla de inspección'],
    d: '40 s vertical. Complementa el post y el vídeo largo de DeCA que ya tenéis apuntados.', x: 'normativa', pre: 'Comprobar la fecha y lo que exige la norma el día que se publique.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Tus fincas en el mapa oficial y el cuaderno digital listo',
    tec: 'Power Apps (Code App), SIGPAC (FEGA), Dataverse', o: 'Code App · Surco',
    g: '«Power Platform también sirve para el campo.»',
    e: 'Las fincas del agricultor sobre el mapa SIGPAC, los tratamientos apuntados y el cuaderno digital de explotación.',
    est: ['Mapa con las fincas coloreadas', 'Apuntar un tratamiento', 'Cuaderno digital generado'],
    d: '45 s vertical.', x: 'normativa', pre: 'Verificar la fecha de obligatoriedad del cuaderno digital antes de publicar.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Plazos procesales que se calculan solos',
    tec: 'Power Apps (Code App), Dataverse', o: 'Code App · Toga',
    g: '«Para un despacho, un plazo mal contado es un problema serio.»',
    e: 'Notificación de LexNET → plazo calculado con festivos → aviso, expediente y portal del cliente.',
    est: ['Calendario con el plazo marcado', 'Notificación entrante', 'Expediente y minutas'],
    d: '45 s vertical.', x: 'construidoYo', pre: 'Antes de publicar: que un abogado revise el cálculo de plazos (está pendiente de validar).' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: PP, t: 'Tu cliente abre la incidencia y sigue la reparación sin llamarte',
    tec: 'Power Pages (sitio de código, React), Dataverse, Power Automate', o: 'Power Pages · Portal SAT',
    g: '«Cada llamada de "¿cómo va lo mío?" es una llamada que puedes ahorrarte.»',
    e: 'El cliente abre la incidencia, ve el estado y recibe avisos; el técnico la cierra.',
    est: ['Vista del cliente con el estado', 'Alta de incidencia', 'Aviso automático al cambiar de estado'],
    d: '40 s vertical.', x: 'construidoYo', pre: 'Demo de «Kelvia».' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'corto', p: PP, t: 'Dónde está mi pedido: seguimiento para una empresa pequeña',
    tec: 'Power Pages, Dataverse, Power Automate', o: 'Power Pages · Seguimiento de pedido',
    g: '«El seguimiento que tienen las grandes tiendas, para tu empresa.»',
    e: 'El cliente mete su número de pedido y ve en qué paso está.',
    est: ['Pantalla del cliente', 'Cambio de estado desde la oficina', 'Aviso al cliente'],
    d: '30 s vertical.', x: 'construidoYo', pre: 'Terminar la página de seguimiento (es un HTML suelto) y grabarla.' },
  { s: 'Una app en 60 segundos', r: A, c: 'linkedin', f: 'carrusel', p: PBI, t: 'Siete áreas de una empresa, siete paneles',
    tec: 'Power BI, DAX, SVG', o: 'Power BI · Catálogo de paneles',
    g: '«Así se ve una empresa entera en siete pantallas.»',
    e: 'Una diapositiva por panel del catálogo: dirección, comercial, compras, producción, calidad, financiero y marketing, con la pregunta que responde cada uno.',
    est: ['Portada: las 7 miniaturas', 'Una diapositiva por panel con su pregunta clave', 'Cierre: «¿Cuál te falta?»'],
    d: 'Carrusel PDF de 9 diapositivas.', x: 'pbiDiseno', pre: 'Capturas en alta de img/paginas de la web de paneles.' },

  // ───────────────────────── Construido con IA
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Construyo una Code App completa con Claude Code en una tarde',
    tec: 'Claude Code, Power Apps (Code App), React, Dataverse, CLI pa', o: 'Skill de Code Apps',
    g: '«De una idea a una app publicada en Power Apps en una tarde. Sin cortar nada.»',
    e: 'Todo el proceso real: brief, dominio, demo, pantallas con el sistema de diseño, tablas de Dataverse y publicación.',
    est: ['Qué vamos a construir y por qué (2 min)', 'Claude Code + skill: dominio y demo', 'Pantallas', 'Dataverse', 'Publicar con pa app push', 'Qué haría distinto'],
    d: '20–25 min, con capítulos. Clip de 60 s para LinkedIn.', x: 'claudeCode', pre: 'Elegir una app pequeña nueva (p. ej. gestión de vehículos de empresa).' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', t: 'Mis skills de Claude para Power Platform: cómo las hago y cómo las uso',
    tec: 'Claude Code, skills, Power Apps, Power BI, CapCut', o: 'Skills IA (Code Apps, Power BI, CapCut, pruebas)',
    g: '«Le he enseñado a Claude a trabajar como nosotros. Estas son las cuatro skills.»',
    e: 'Qué es una skill, cómo está hecha la de Code Apps, la de Power BI, la de CapCut y la de pruebas, y una demo de cada una.',
    est: ['Qué es una skill', 'Skill de Code Apps', 'Skill de Power BI', 'Skill de CapCut', 'Skill de pruebas', 'Cómo crear la tuya'],
    d: '15–18 min.', x: 'jesusCanal', pre: 'Enseñar las skills sin datos de clientes.' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Claude Code + Dataverse: las tablas de una app creadas con un script',
    tec: 'Claude Code, Dataverse Web API, Node.js', o: 'Scripts de esquema de la app interna',
    g: '«Doce tablas, sus relaciones y sus opciones, creadas en dos minutos y repetibles.»',
    e: 'Cómo pedir el esquema a Claude, el script idempotente y cómo llevarlo de un entorno a otro.',
    est: ['El problema de crear tablas a mano', 'Pedir el esquema', 'Ejecutar el script', 'Repetirlo en otro entorno'],
    d: '12 min.', x: 'claudeCode', pre: 'Entorno de pruebas limpio.' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', p: CA, t: 'La IA prueba mi app sola: la skill de testing de Code Apps',
    tec: 'Claude Code, Playwright, Power Apps (Code App)', o: 'Skill de testing de Code Apps',
    g: '«Antes de entregar una app, la IA la usa como lo haría tu equipo.»',
    e: 'La skill abre la app, recorre las pantallas, encuentra fallos y los arregla.',
    est: ['Por qué probar', 'La skill en marcha', 'Un fallo real encontrado', 'Arreglo y vuelta a probar'],
    d: '10–12 min.', x: 'claudeCode', pre: 'Tener un fallo real reproducible para enseñar.' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Modelos 3D dentro de una Power App, escritos por la IA',
    tec: 'Claude Code, Three.js, Power Apps (Code App)', o: 'Code Apps · Producción, Almacén, Parque, Inspección',
    g: '«Nadie te ha enseñado esto en Power Apps: modelos 3D interactivos.»',
    e: 'Cómo se modela la bomba de Producción y el almacén por código, cómo se integra en la Code App y cómo se mantiene fluido en una tablet.',
    est: ['El resultado', 'Modelar por código con Claude', 'Integrarlo en React', 'Rendimiento en tablet'],
    d: '15 min. Clip de 45 s para LinkedIn.', x: 'produccionHueco', pre: 'Grabar a 60 fps.' },
  { s: 'Construido con IA', r: J, c: 'linkedin', f: 'post', t: 'Vibe coding en Power Platform: qué sale bien y qué no',
    tec: 'Claude Code, GitHub Copilot, Power Apps (Code App)', o: 'Experiencia con todas las Code Apps',
    g: '«He construido 14 apps con IA en los últimos meses. Esto es lo que sale bien y lo que todavía no.»',
    e: 'Lista honesta: lo que la IA hace muy bien (pantallas, demos, scripts) y dónde hay que estar encima (seguridad, licencias, datos reales).',
    est: ['Gancho con el número', '3 cosas que sale bien', '3 que no', 'Pregunta: ¿qué os ha pasado a vosotros?'],
    d: 'Post de texto de 250–350 palabras.', x: 'codeApps', pre: '—' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Copilot, ChatGPT o Claude: la misma Power App con los tres',
    tec: 'Copilot Cowork, ChatGPT, Claude Code, Power Apps', o: '—',
    g: '«Le pedí la misma app a tres IA. Solo una llegó a producción.»',
    e: 'El mismo encargo a las tres, con cronómetro, y el resultado evaluado: diseño, datos, errores y si se puede mantener.',
    est: ['El encargo', 'Copilot', 'ChatGPT', 'Claude', 'Veredicto con tabla'],
    d: '18–20 min. Carrusel con la tabla del veredicto.', x: 'cowork', pre: 'Encargo igual para las tres y cronómetro en pantalla.' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', t: 'Copilot Cowork ya crea aplicaciones: lo ponemos a prueba',
    tec: 'Copilot Cowork, Power Apps', o: '—',
    g: '«Microsoft dice que Copilot ya crea apps de verdad. Lo comprobamos con un caso de empresa.»',
    e: 'Prueba honesta de la novedad con un proceso real de una empresa mediana (de demo).',
    est: ['Qué promete', 'Prueba', 'Dónde se queda corto', 'Cuándo usarlo y cuándo no'],
    d: '12 min.', x: 'cowork', pre: 'Comprobar que está disponible en el tenant.' },
  { s: 'Construido con IA', r: J, c: 'youtube', f: 'largo', t: 'Así editamos nuestros vídeos con IA: CapCut + Remotion',
    tec: 'Claude Code, CapCut, Remotion', o: 'Skill de CapCut y animaciones del vídeo de presentación',
    g: '«Este vídeo lo ha editado una IA. Te enseño cómo.»',
    e: 'La skill que quita silencios, añade zooms y subtítulos, y las animaciones de marca hechas con código.',
    est: ['Resultado', 'Transcripción y cortes', 'Zooms y subtítulos', 'Animaciones con Remotion'],
    d: '12 min.', x: 'claudeCode', pre: 'Usar como ejemplo el vídeo de presentación de locodea.' },

  // ───────────────────────── Power BI con IA
  { s: 'Power BI con IA', r: J, c: 'youtube', f: 'largo', p: PBI, t: 'El panel de producción, entero con Claude y el MCP de Power BI',
    tec: 'Power BI (PBIP), MCP de Power BI, Claude Code, DAX, SVG', o: 'Power BI · Panel de Producción',
    g: '«Un Power BI de producción completo, sin tocar el ratón.»',
    e: 'Segunda parte de tu vídeo más visto, ahora con producción: modelo, medidas, páginas y la planta en 3D.',
    est: ['Resultado final', 'Modelo y medidas', 'Páginas y visuales', 'Gráfico personalizado en SVG', 'Publicar'],
    d: '25–30 min.', x: 'claudePBI', pre: 'Enlazar al primer vídeo en la descripción.' },
  { s: 'Power BI con IA', r: A, c: 'linkedin', f: 'corto', p: PBI, t: 'La planta en 3D, dentro de Power BI',
    tec: 'Power BI, three.js, DAX', o: 'Power BI · Panel de Producción / web de paneles',
    g: '«Esto es un Power BI. Sí, en 3D.»',
    e: 'Cada máquina en verde, ámbar o rojo según rinde frente a su objetivo.',
    est: ['Giro de la planta', 'Clic en una máquina roja', 'Detalle de la máquina'],
    d: '30 s vertical.', x: 'claudePBI', pre: 'Grabar la planta 3D de la web de paneles.' },
  { s: 'Power BI con IA', r: J, c: 'youtube', f: 'largo', p: PBI, t: 'Gráficos que Power BI no trae: dibujados en DAX con SVG',
    tec: 'Power BI, DAX, SVG', o: 'Skill de Power BI',
    g: '«Este gráfico no existe en Power BI. Lo he dibujado con una medida.»',
    e: 'Cómo se construye un gráfico propio (progreso, semáforo, sparkline) con una medida DAX que devuelve SVG.',
    est: ['Resultado', 'La idea del SVG en DAX', 'Tres gráficos paso a paso', 'Plantilla para llevarte'],
    d: '15 min. Carrusel de Alejandro con los 3 gráficos.', x: 'pbiDiseno', pre: 'Preparar plantilla descargable.' },
  { s: 'Power BI con IA', r: A, c: 'linkedin', f: 'corto', p: PBI, t: 'Rediseño un Power BI feo en 60 segundos',
    tec: 'Power BI, tema JSON, fondos de marca', o: 'Power BI · Fondos locodea',
    g: '«Mismo informe, mismos datos. Solo cambia el diseño.»',
    e: 'Antes y después de un informe de ejemplo: fondo, márgenes, tres colores y tarjetas.',
    est: ['El antes', '5 cambios en cámara rápida', 'El después con barrido'],
    d: '45 s vertical.', x: 'tipsDiseno', pre: 'Un informe «feo» de ejemplo con datos inventados.' },
  { s: 'Power BI con IA', r: J, c: 'youtube', f: 'largo', p: PBI, t: 'Power BI Report Skills contra nuestra skill: probamos las dos',
    tec: 'Power BI, Report Skills, Claude Code', o: 'Skill de Power BI',
    g: '«Microsoft ha sacado sus skills de informes. ¿Mejor que la nuestra?»',
    e: 'El mismo informe con las dos y comparación honesta.',
    est: ['Qué son', 'Prueba con Report Skills', 'Prueba con la nuestra', 'Veredicto'],
    d: '15 min.', x: 'reportSkills', pre: '—' },
  { s: 'Power BI con IA', r: J, c: 'youtube', f: 'largo', t: 'Fabric Apps: ¿se acaban los informes de Power BI?',
    tec: 'Microsoft Fabric, Power BI', o: '—',
    g: '«Se está diciendo que las Fabric Apps sustituyen a Power BI. Lo probamos.»',
    e: 'Qué son, qué aportan a una empresa mediana y cuándo no merecen la pena por coste.',
    est: ['La promesa', 'Demo', 'Coste de capacidad', 'Opinión'],
    d: '12 min.', x: 'fabricApps', pre: 'Revisar el coste de capacidad de Fabric antes de grabar.' },
  { s: 'Power BI con IA', r: A, c: 'linkedin', f: 'carrusel', p: PBI, t: 'El panel del gerente: las 5 cifras que miraría cada mañana',
    tec: 'Power BI', o: 'Power BI · Panel de Dirección',
    g: '«Si solo pudieras mirar cinco cifras de tu empresa, deberían ser estas.»',
    e: 'Ventas, margen, cobros pendientes, entregas en riesgo y horas: por qué cada una y cómo se ve.',
    est: ['Portada', 'Una cifra por diapositiva con su visual', 'Cierre con el panel completo'],
    d: 'Carrusel de 7 diapositivas.', x: 'datosPropios', pre: 'Capturas del panel de dirección.' },
  { s: 'Power BI con IA', r: J, c: 'youtube', f: 'largo', p: PBI, t: 'Panel de personas: Power BI con los datos de Jornada y Formación',
    tec: 'Power BI, Dataverse, Power Apps (Code App)', o: 'Code Apps · Jornada y Formación',
    g: '«Horas, vacaciones y formación de tu equipo en un panel que se actualiza solo.»',
    e: 'Conectar Power BI a las tablas de las apps y construir el panel de personas.',
    est: ['Resultado', 'Conexión a Dataverse', 'Modelo', 'Páginas'],
    d: '15 min.', x: 'pbiDiseno', pre: 'Pasar Jornada y Formación a Dataverse con datos de demo.' },

  // ───────────────────────── Automatiza esto (Power Automate)
  { s: 'Automatiza esto', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Este flujo lee las facturas de proveedor con IA y las cuadra con el pedido',
    tec: 'Power Automate, AI Builder / prompts de Copilot, Dataverse, Outlook', o: 'Code App · Compras (flujo nuevo)',
    g: '«La factura entra por correo y se cuadra sola con el pedido y el albarán.»',
    e: 'Buzón → lectura con IA → cruce con pedido y albarán → aviso si no cuadra.',
    est: ['Resultado', 'Disparador de correo', 'Lectura con IA', 'Cruce a tres bandas', 'Aviso'],
    d: '15 min + corto de 45 s (Alejandro).', x: 'facturasIA', pre: 'Construir el flujo; facturas de ejemplo inventadas.' },
  { s: 'Automatiza esto', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Aprobar una compra desde Teams con un clic',
    tec: 'Power Automate, Teams (tarjetas adaptables), Dataverse', o: 'Code App · Compras (flujo nuevo)',
    g: '«Antes: una cadena de correos para aprobar una compra. Ahora: un clic en el móvil.»',
    e: 'La solicitud llega a Teams como tarjeta, se aprueba y el pedido sale solo.',
    est: ['Notificación en el móvil', 'Aprobar', 'El pedido cambia de estado en la app'],
    d: '30 s vertical.', x: 'workflows', pre: 'Construir el flujo de aprobación.' },
  { s: 'Automatiza esto', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Aviso de stock bajo con el pedido al proveedor ya preparado',
    tec: 'Power Automate, Dataverse, Outlook', o: 'Code App · Almacén + Compras (flujo nuevo)',
    g: '«Tu almacén avisa antes de quedarse sin material.»',
    e: 'Cuando un artículo baja del mínimo, se prepara el borrador de pedido y se avisa al responsable.',
    est: ['Aviso en el correo', 'Borrador de pedido', 'Enviarlo al proveedor'],
    d: '35 s vertical.', x: 'workflows', pre: 'Construir el flujo.' },
  { s: 'Automatiza esto', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Licencias y garantías que caducan: el flujo que avisa 30 días antes',
    tec: 'Power Automate, Dataverse, Outlook', o: 'Code App · Parque (flujo nuevo)',
    g: '«Esa licencia caduca el mes que viene. Tu empresa ya lo sabe.»',
    e: 'Flujo programado que revisa licencias, garantías y contratos y avisa con antelación.',
    est: ['Correo de aviso', 'La ficha en Parque', 'Renovar'],
    d: '30 s vertical.', x: 'workflows', pre: 'Construir el flujo.' },
  { s: 'Automatiza esto', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Alta de un empleado en un solo formulario: portátil, cursos y fichaje',
    tec: 'Power Automate, Dataverse, Power Apps (Code Apps), Outlook', o: 'Code Apps · Parque, Formación y Jornada (flujo nuevo)',
    g: '«Una persona entra en la empresa. Un formulario. Todo lo demás, solo.»',
    e: 'El flujo que conecta tres apps: le asigna portátil en Parque, cursos en Formación y turno en Jornada. Es el mensaje de «digitalizar la mayor parte de los procesos» hecho demo.',
    est: ['El formulario', 'Lo que pasa en Parque', 'En Formación', 'En Jornada', 'El correo de bienvenida'],
    d: '15 min + corto de 60 s.', x: 'workflows', pre: 'Las tres apps en Dataverse con datos de demo.' },
  { s: 'Automatiza esto', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'El parte firmado en la tablet llega en PDF al cliente',
    tec: 'Power Automate, plantilla de Word, Dataverse, Outlook', o: 'Code App · Inspección (flujo nuevo)',
    g: '«Firma en la tablet. El cliente ya tiene su informe en el correo.»',
    e: 'Al cerrar la inspección se genera el PDF con la plantilla de la empresa y se envía.',
    est: ['Firma', 'PDF generado', 'Correo del cliente'],
    d: '30 s vertical.', x: 'workflows', pre: 'Construir el flujo y la plantilla.' },
  { s: 'Automatiza esto', r: J, c: 'youtube', f: 'largo', t: 'El resumen semanal de tu empresa en el correo, escrito por IA',
    tec: 'Power Automate, prompts de IA (AI Builder), Dataverse, Power BI', o: 'Flujo nuevo sobre los datos de las apps',
    g: '«Cada semana, un correo que te cuenta cómo va tu empresa. Lo escribe la IA.»',
    e: 'Flujo programado que recoge cifras de las apps, las pasa por un prompt y envía un resumen legible.',
    est: ['El correo recibido', 'Recoger datos', 'El prompt', 'Enviar'],
    d: '12 min.', x: 'agenteM365', pre: 'Construir el flujo.' },
  { s: 'Automatiza esto', r: A, c: 'linkedin', f: 'carrusel', t: '5 automatizaciones que ya incluye tu Microsoft 365 y no usas',
    tec: 'Power Automate, Microsoft Forms, Listas de Microsoft, Teams', o: '—',
    g: '«Ya las estás pagando. Y probablemente no las usas.»',
    e: 'Cinco flujos con licencia estándar: aprobaciones, formularios a lista, recordatorios, adjuntos a SharePoint, avisos en Teams.',
    est: ['Portada', 'Una automatización por diapositiva', 'Cierre: «¿Cuál montas primero?»'],
    d: 'Carrusel de 7 diapositivas.', x: 'm365malUso', pre: 'Comprobar que todas funcionan con licencia estándar.' },
  { s: 'Automatiza esto', r: J, c: 'youtube', f: 'largo', t: 'Un flujo que llama a un agente de IA y espera su respuesta',
    tec: 'Power Automate, Copilot Studio', o: 'Flujo nuevo',
    g: '«El flujo pregunta a un agente de IA, espera la respuesta y sigue.»',
    e: 'Clasificar un correo de cliente con un agente y decidir el siguiente paso según la respuesta.',
    est: ['Caso', 'Crear el agente', 'Llamarlo desde el flujo', 'Usar la respuesta'],
    d: '12 min.', x: 'agenteFlujo', pre: 'Comprobar el coste de mensajes de Copilot Studio.' },
  { s: 'Automatiza esto', r: J, c: 'linkedin', f: 'post', p: CA, t: 'La conciliación a tres bandas, automática',
    tec: 'Power Automate, Dataverse', o: 'Code App · Compras',
    g: '«Pedido, albarán y factura. Si no cuadran, te enteras antes de pagar.»',
    e: 'Qué es la conciliación a tres bandas, por qué importa en una empresa mediana y cómo la hace sola la app.',
    est: ['Gancho', 'Qué es en 3 líneas', 'Qué hace la app', 'Pregunta'],
    d: 'Post + captura.', x: 'nichoES', pre: 'Captura de la pantalla de conciliación.' },

  // ───────────────────────── Agentes de IA con Microsoft
  { s: 'Agentes de IA con Microsoft', r: J, c: 'youtube', f: 'largo', p: CA, t: 'Un agente que responde «¿cuántas vacaciones me quedan?»',
    tec: 'Copilot Studio, Dataverse, Teams', o: 'Code App · Jornada (agente nuevo)',
    g: '«Tu equipo pregunta en Teams y el agente contesta con sus datos reales.»',
    e: 'Agente de Copilot Studio conectado a las tablas de Jornada: vacaciones, horas y turnos.',
    est: ['Pregunta en Teams', 'Crear el agente', 'Conectar Dataverse', 'Publicar en Teams'],
    d: '15 min + corto de 30 s.', x: 'agenteM365', pre: 'Jornada en Dataverse con datos de demo.' },
  { s: 'Agentes de IA con Microsoft', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Pregúntale al almacén dónde está una pieza',
    tec: 'Copilot Studio, Dataverse', o: 'Code App · Almacén (agente nuevo)',
    g: '«"¿Dónde está la fresa de 12?" Y te lo marca en el mapa.»',
    e: 'El agente responde con la ubicación y la cantidad.',
    est: ['Pregunta', 'Respuesta', 'El mapa 3D con la ubicación'],
    d: '30 s vertical.', x: 'agenteES', pre: 'Construir el agente.' },
  { s: 'Agentes de IA con Microsoft', r: J, c: 'youtube', f: 'largo', p: PP, t: 'Un agente de soporte en el portal que abre la incidencia por ti',
    tec: 'Copilot Studio, Power Pages, Dataverse', o: 'Power Pages · Portal SAT (agente nuevo)',
    g: '«El cliente explica su problema y el agente abre la incidencia bien rellenada.»',
    e: 'Agente embebido en el Portal SAT que hace las preguntas correctas y crea el registro.',
    est: ['Conversación', 'Crear el agente', 'Acción para crear la incidencia', 'Insertarlo en el portal'],
    d: '15 min.', x: 'agenteM365', pre: 'Construir el agente.' },
  { s: 'Agentes de IA con Microsoft', r: J, c: 'youtube', f: 'largo', t: 'Tu primer agente con Copilot Studio en 15 minutos, en español',
    tec: 'Copilot Studio', o: '—',
    g: '«Tu primer agente de IA de empresa, sin programar, en un cuarto de hora.»',
    e: 'Tutorial desde cero con un caso de empresa: el agente que responde con la documentación interna.',
    est: ['Qué vamos a hacer', 'Crear', 'Fuentes de conocimiento', 'Probar', 'Publicar'],
    d: '15 min exactos (el título lo promete).', x: 'agenteES', pre: '—' },
  { s: 'Agentes de IA con Microsoft', r: J, c: 'youtube', f: 'largo', t: 'El nuevo agente de flujos de Copilot, probado con un caso de empresa',
    tec: 'Copilot (flujos de trabajo), Power Automate', o: '—',
    g: '«Microsoft dice que este agente automatiza tu trabajo. Lo probamos con un proceso real.»',
    e: 'Prueba honesta con un proceso de compras o de personal.',
    est: ['Qué es', 'Prueba', 'Límites', 'Veredicto'],
    d: '12 min.', x: 'workflows', pre: 'Comprobar disponibilidad y licencia.' },
  { s: 'Agentes de IA con Microsoft', r: J, c: 'linkedin', f: 'post', t: '¿Van a sustituir los agentes de IA a las aplicaciones de empresa?',
    tec: 'Copilot Studio, Power Apps', o: 'Experiencia con apps y agentes',
    g: '«Después de construir las dos cosas, mi respuesta es que no. Pero lo cambian todo.»',
    e: 'Opinión: cuándo basta un agente, cuándo hace falta una app y cómo se combinan.',
    est: ['Gancho', 'Argumento', 'Ejemplo con Jornada', 'Pregunta abierta'],
    d: 'Post de 300 palabras.', x: 'nichoES', pre: '—' },
  { s: 'Agentes de IA con Microsoft', r: J, c: 'linkedin', f: 'corto', t: 'El agente que te dice cuánto te cuestan las licencias de Microsoft',
    tec: 'Copilot Studio, SharePoint', o: 'Agente nuevo',
    g: '«Le preguntas cuántas licencias necesitas para tu app y te lo calcula.»',
    e: 'Agente con la documentación oficial de licencias que responde con escenarios de 10, 50 y 150 usuarios.',
    est: ['Pregunta', 'Respuesta con cálculo', 'Enlace a la fuente'],
    d: '40 s vertical.', x: 'agenteLicencias', pre: 'Cargar documentación oficial actualizada y revisar cada cifra.' },

  // ───────────────────────── Business Central + Power Platform
  { s: 'Business Central + Power Platform', r: J, c: 'youtube', f: 'largo', t: 'El agente de facturas de proveedor de Business Central: veredicto honesto',
    tec: 'Business Central, agentes de Copilot', o: '—',
    g: '«He probado el agente de facturas de Business Central. Esto es lo que hace de verdad.»',
    e: 'Prueba con facturas de ejemplo: qué lee bien, qué falla y cuándo compensa.',
    est: ['Qué promete', 'Prueba', 'Fallos', 'Veredicto'],
    d: '12 min + post en LinkedIn con el veredicto.', x: 'bcAgente', pre: 'Entorno de pruebas de Business Central.' },
  { s: 'Business Central + Power Platform', r: J, c: 'youtube', f: 'largo', p: PBI, t: 'Power BI sobre Business Central en una tarde',
    tec: 'Business Central, Power BI, Claude Code', o: 'Power BI · Catálogo',
    g: '«Tus datos de Business Central en un panel de dirección, en una tarde.»',
    e: 'Conexión, modelo y panel, con ayuda de Claude.',
    est: ['Resultado', 'Conexión', 'Modelo', 'Panel'],
    d: '20 min.', x: 'claudePBI', pre: 'Entorno de pruebas de Business Central.' },
  { s: 'Business Central + Power Platform', r: J, c: 'linkedin', f: 'post', t: 'Extender Business Central con una app: cuándo sí y cuándo no',
    tec: 'Business Central, Power Apps (Code App)', o: '—',
    g: '«No todo se arregla con una extensión de AL. Ni con una app.»',
    e: 'Criterio para elegir entre extensión, app de Power Platform o nada.',
    est: ['Gancho', '3 casos para app', '3 casos para extensión', 'Pregunta'],
    d: 'Post o carrusel.', x: 'nichoES', pre: '—' },
  { s: 'Business Central + Power Platform', r: J, c: 'youtube', f: 'largo', t: 'Calidad en Business Central 2026 más nuestra app de no conformidades',
    tec: 'Business Central, Power Apps (Code App), Dataverse', o: 'Code Apps · Compras y Formación (ISO 9001)',
    g: '«Business Central ya trae gestión de calidad. Esto es lo que le falta a una empresa con ISO 9001.»',
    e: 'Lo nuevo de calidad en Business Central y cómo se completa con apps.',
    est: ['Novedad', 'Demo', 'Lo que falta', 'Cómo lo cubrimos'],
    d: '15 min.', x: 'bcAgente', pre: 'Verificar qué incluye la versión vigente.' },

  // ───────────────────────── Normativa que llega
  { s: 'Normativa que llega', r: A, c: 'linkedin', f: 'carrusel', p: PP, t: 'DeCA: lo que cambia en el transporte, en 5 diapositivas',
    tec: 'Power Pages', o: 'Power Pages · DeCA',
    g: '«Si cargas o transportas mercancía por carretera, esto te afecta.»',
    e: 'Qué es, a quién afecta, desde cuándo, qué pasa si no lo llevas y cómo se ve en el móvil.',
    est: ['Portada', 'Qué es', 'A quién afecta', 'Qué pasa si no', 'Cómo se hace'],
    d: 'Carrusel de 6 diapositivas. Complementa el post de DeCA que ya tenéis.', x: 'normativa', pre: 'Comprobar la norma y las sanciones el día de publicar.' },
  { s: 'Normativa que llega', r: J, c: 'linkedin', f: 'post', p: CA, t: 'Cuaderno digital de explotación: lo que viene para el campo',
    tec: 'Power Apps (Code App), SIGPAC', o: 'Code App · Surco',
    g: '«Si aplicas fitosanitarios, tu cuaderno de campo pasa a ser digital.»',
    e: 'Qué exige, desde cuándo y cómo lo resuelve Surco.',
    est: ['Gancho', 'Qué cambia', 'Cómo lo hacemos', 'Pregunta'],
    d: 'Post + vídeo corto de Surco.', x: 'normativa', pre: 'Verificar la fecha oficial.' },
  { s: 'Normativa que llega', r: J, c: 'linkedin', f: 'post', p: CA, t: 'Registro de jornada: qué tiene que guardar tu empresa',
    tec: 'Power Apps (Code App), Dataverse', o: 'Code App · Jornada',
    g: '«¿Tu registro de jornada aguantaría una inspección de trabajo?»',
    e: 'Qué exige la norma vigente y cómo lo cumple Jornada dentro de Microsoft 365.',
    est: ['Pregunta', 'Qué exige', 'Cómo lo resolvemos', 'Pregunta final'],
    d: 'Post + capturas.', x: 'normativa', pre: 'Revisar la norma vigente antes de publicar.' },
  { s: 'Normativa que llega', r: J, c: 'linkedin', f: 'post', t: 'VeriFactu y facturación: qué hacemos (y qué no) desde Power Platform',
    tec: 'Power Platform, Business Central', o: 'App interna · decisión de no construir ERP',
    g: '«No vamos a hacerte un programa de facturación. Te explico por qué.»',
    e: 'Por qué la factura oficial debe ir en software certificado y qué sí se automatiza alrededor.',
    est: ['Gancho', 'El motivo', 'Lo que sí hacemos', 'Pregunta'],
    d: 'Post de 300 palabras.', x: 'normativa', pre: 'Confirmar fechas con la AEAT.' },
  { s: 'Normativa que llega', r: A, c: 'linkedin', f: 'carrusel', t: 'Calendario de obligaciones digitales 2026–2027 para tu empresa',
    tec: '—', o: 'DeCA, Surco, Jornada',
    g: '«Cinco fechas que tu empresa debería tener en el calendario.»',
    e: 'DeCA, cuaderno digital, factura electrónica, VeriFactu y registro de jornada, con la app o la acción para cada una.',
    est: ['Portada', 'Una obligación por diapositiva', 'Cierre'],
    d: 'Carrusel de 7 diapositivas; puede ser descargable.', x: 'normativa', pre: 'Verificar cada fecha en BOE o AEAT.' },

  // ───────────────────────── Diseño que se usa
  { s: 'Diseño que se usa', r: A, c: 'linkedin', f: 'carrusel', t: 'Por qué nuestras apps no parecen de Power Apps',
    tec: 'Power Apps (Code App), React, sistema de diseño Bronce', o: 'Sistema de diseño locodea.',
    g: '«Esto es una Power App. Aunque no lo parezca.»',
    e: 'Tipografía, color, espacios, bordes y componentes propios frente a una app de Power Apps por defecto.',
    est: ['Antes/después', 'Tipografía', 'Color medido', 'Componentes propios', 'Por qué importa: la gente la usa'],
    d: 'Carrusel de 8 diapositivas + corto de 30 s.', x: 'tipsDiseno', pre: 'Una app de lienzo por defecto para el «antes».' },
  { s: 'Diseño que se usa', r: A, c: 'linkedin', f: 'carrusel', p: CA, t: 'Diseñar para una tablet de planta: botones grandes y cero menús',
    tec: 'Power Apps (Code App)', o: 'Code App · Producción',
    g: '«El operario lleva guantes, está de pie y tiene prisa. Tu app tiene que saberlo.»',
    e: 'Las decisiones de diseño de Producción: botón enorme, un paso por pantalla, contraste y colores de estado.',
    est: ['Gancho', '5 reglas con captura cada una', 'Cierre'],
    d: 'Carrusel de 7 diapositivas.', x: 'tipsDiseno', pre: 'Capturas de Producción.' },
  { s: 'Diseño que se usa', r: A, c: 'youtube', f: 'largo', t: 'Del boceto en papel a la app publicada',
    tec: 'Power Apps (Code App), Figma, Claude Code', o: 'Cualquier Code App del catálogo',
    g: '«Así nace una app en locodea.: de un papel a producción.»',
    e: 'Boceto, sistema de diseño, pantallas y publicación, contado por quien diseña.',
    est: ['Boceto', 'Componentes', 'Pantallas', 'Publicación'],
    d: '12–15 min.', x: 'tipsDiseno', pre: 'Grabar el boceto real en papel.' },
  { s: 'Diseño que se usa', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Una app con tu logo en 5 segundos: marca blanca y modo oscuro',
    tec: 'Power Apps (Code App)', o: 'Code Apps · Jornada y CRM',
    g: '«Misma app. Tu logo, tu color y el nombre que verá tu equipo.»',
    e: 'Cambio de marca y tema oscuro en directo.',
    est: ['Marca A', 'Cambio', 'Marca B', 'Modo oscuro'],
    d: '20 s vertical.', x: 'construidoYo', pre: '—' },
  { s: 'Diseño que se usa', r: A, c: 'youtube', f: 'largo', t: 'Un sistema de diseño para Power Apps: tokens, tipografía y componentes',
    tec: 'Power Apps (Code App), CSS, React', o: 'Sistema de diseño locodea. y plantilla de Code Apps',
    g: '«Todas nuestras apps parecen de la misma marca. Así lo conseguimos.»',
    e: 'Tokens de color, tipografía empaquetada, desplegables propios y tema oscuro.',
    est: ['Por qué', 'Tokens', 'Componentes', 'Aplicarlo a una app nueva'],
    d: '15 min.', x: 'tipsDiseno', pre: '—' },
  { s: 'Diseño que se usa', r: A, c: 'linkedin', f: 'carrusel', t: '3 trucos de diseño para que tu equipo sí use la app',
    tec: 'Power Apps', o: 'Code Apps del catálogo',
    g: '«La app más útil del mundo no sirve si nadie la abre.»',
    e: 'Menos campos, estados vacíos que explican qué hacer y una acción principal por pantalla.',
    est: ['Gancho', 'Truco 1', 'Truco 2', 'Truco 3', 'Cierre'],
    d: 'Carrusel de 5 diapositivas.', x: 'tipsDiseno', pre: '—' },
  { s: 'Diseño que se usa', r: A, c: 'linkedin', f: 'corto', t: 'Ocho horas de desarrollo en 40 segundos',
    tec: 'Power Apps (Code App), Claude Code', o: 'Cualquier Code App',
    g: '«Un día entero de trabajo, en 40 segundos.»',
    e: 'Cámara rápida de la construcción de una pantalla, de vacío a terminada.',
    est: ['Pantalla vacía', 'Cámara rápida', 'Resultado'],
    d: '40 s vertical con música.', x: 'construidoYo', pre: 'Grabar la pantalla todo un día de desarrollo.' },

  // ───────────────────────── He analizado…
  { s: 'He analizado…', r: J, c: 'linkedin', f: 'carrusel', p: CA, t: 'He comparado 9 herramientas de proyectos: las quejas que más se repiten',
    tec: '—', o: 'Code App · Proyectos (docs/ANALISIS.md)',
    g: '«Planner, Asana, Monday, ClickUp… He leído sus reseñas. Estas son las 5 quejas que más se repiten.»',
    e: 'Las quejas más repetidas según el análisis y cómo las resolvimos en nuestra app.',
    est: ['Portada', 'Una queja por diapositiva', 'Cómo lo resolvemos', 'Cierre'],
    d: 'Carrusel de 8 diapositivas.', x: 'datosPropios', pre: 'Sacar los datos de docs/ANALISIS.md.' },
  { s: 'He analizado…', r: J, c: 'linkedin', f: 'post', p: CA, t: 'Coupa, Ariba u Odoo para compras: qué le sirve a una empresa mediana',
    tec: '—', o: 'Code App · Compras (docs/analisis-y-propuesta.md)',
    g: '«Las grandes herramientas de compras cuestan lo que un sueldo. Esto es lo que una empresa mediana usa de verdad.»',
    e: 'Resumen del análisis: qué aporta cada herramienta y qué necesita de verdad una empresa pequeña o mediana.',
    est: ['Gancho', '3 aprendizajes', 'Qué hicimos', 'Pregunta'],
    d: 'Post o carrusel.', x: 'datosPropios', pre: 'Revisar las cifras del análisis antes de citarlas.' },
  { s: 'He analizado…', r: J, c: 'linkedin', f: 'post', p: CA, t: 'Programas de fichaje por suscripción o tu Microsoft 365: la comparación',
    tec: '—', o: 'Code App · Jornada',
    g: '«Pagar por persona y mes el fichaje, o tenerlo dentro de lo que ya usas.»',
    e: 'Comparación de enfoque: datos, coste por usuario y dependencia del proveedor.',
    est: ['Gancho', 'Tabla comparativa', 'Opinión', 'Pregunta'],
    d: 'Post + imagen con tabla.', x: 'licencias', pre: 'Verificar tarifas públicas el día de publicar; no citar precios sin fuente.' },
  { s: 'He analizado…', r: J, c: 'linkedin', f: 'post', t: '46.426 talleres en España: por qué nadie les hace la inspección digital «pro»',
    tec: 'Power Apps (Code App), Three.js', o: 'Idea Rampa (análisis de mercado)',
    g: '«Hay más de 46.000 talleres en España. Casi todos facturan con programas de 10–80 € al mes. Ninguno enseña el coche en 3D al cliente.»',
    e: 'El hueco que encontramos en el análisis y la idea de Rampa.',
    est: ['Dato', 'Lo que funciona en EE. UU.', 'El hueco', 'La idea'],
    d: 'Post de 300 palabras.', x: 'datosPropios', pre: 'Citar la fuente del dato; Rampa es una idea, no una app hecha.' },
  { s: 'He analizado…', r: J, c: 'linkedin', f: 'carrusel', p: CA, t: 'Software para despachos: lo que echan en falta los abogados',
    tec: '—', o: 'Code App · Toga (docs/analisis-y-propuesta.md)',
    g: '«He revisado los programas que usan los despachos. Estos son los huecos.»',
    e: 'Resumen del análisis de software jurídico y cómo lo cubre Toga.',
    est: ['Portada', 'Huecos', 'Cómo lo cubrimos'],
    d: 'Carrusel de 6 diapositivas.', x: 'datosPropios', pre: 'Validación de un abogado antes de presentar Toga.' },
  { s: 'He analizado…', r: J, c: 'linkedin', f: 'post', p: CA, t: 'CRM para empresas pequeñas: lo que pagan y lo que usan',
    tec: '—', o: 'Code App · CRM (docs/analisis-mercado.md)',
    g: '«Muchas empresas pequeñas pagan un CRM entero y usan una parte.»',
    e: 'Datos del análisis de mercado del CRM.',
    est: ['Gancho', 'Datos', 'Opinión', 'Pregunta'],
    d: 'Post. Complementa la idea que ya tenéis de comparar con un CRM caro.', x: 'datosPropios', pre: 'Citar solo datos que estén en el análisis.' },

  // ───────────────────────── Detrás de locodea.
  { s: 'Detrás de locodea.', r: J, c: 'youtube', f: 'largo', t: 'Así gestionamos locodea. con nuestra propia app',
    tec: 'Power Apps (Code App), Dataverse, Outlook', o: 'App interna · Proyectos y Tareas',
    g: '«Lo que vendemos, lo usamos primero.»',
    e: 'Objetivos semanales, tareas, reuniones con Outlook, el CRM y este banco de ideas.',
    est: ['Por qué la hicimos', 'Recorrido', 'Lo que aprendimos usándola'],
    d: '12 min + post de LinkedIn.', x: 'construidoYo', pre: 'Ocultar datos sensibles.' },
  { s: 'Detrás de locodea.', r: A, c: 'linkedin', f: 'corto', t: 'Nuestro banco de ideas de contenido, votado con estrellas',
    tec: 'Power Apps (Code App), Dataverse', o: 'App interna · Contenido',
    g: '«90 ideas de contenido. Las votamos con estrellas. Esta es la que ganó.»',
    e: 'El apartado de Contenido con las valoraciones y la idea elegida.',
    est: ['El banco', 'Votando', 'La ganadora'],
    d: '30 s vertical.', x: 'construidoYo', pre: 'Hacerlo cuando ya estén votadas.' },
  { s: 'Detrás de locodea.', r: A, c: 'linkedin', f: 'post', t: 'Las empresas inventadas de nuestras demos',
    tec: '—', o: 'Demos de todas las apps',
    g: '«Ferralta, Duvaria, Almenara, Arcos Vidal… Ninguna existe. Te explico por qué.»',
    e: 'Por qué nunca enseñamos datos de clientes y cómo creamos demos creíbles.',
    est: ['Gancho', 'Por qué', 'Cómo', 'Cierre'],
    d: 'Post ligero con imagen de los logos inventados.', x: 'nichoES', pre: '—' },
  { s: 'Detrás de locodea.', r: J, c: 'youtube', f: 'largo', t: 'Cómo publicamos una Code App en un entorno sin sustos',
    tec: 'Power Apps (Code App), soluciones, CLI pa, Git', o: 'App interna · script de publicación',
    g: '«Compilar, publicar en la solución y guardar en Git con un solo comando.»',
    e: 'El script de publicación, las soluciones y cómo se pasa de desarrollo a producción.',
    est: ['El problema', 'Soluciones', 'El script', 'Paso a producción'],
    d: '12 min.', x: 'codeApps', pre: '—' },
  { s: 'Detrás de locodea.', r: J, c: 'linkedin', f: 'post', t: 'Lo que cuesta de verdad en licencias tener 5 apps en Microsoft 365',
    tec: 'Power Apps Premium, Dataverse', o: 'App interna (README: por qué Dataverse)',
    g: '«Microsoft retiró la licencia de Power Apps de 5 $. Esto es lo que cuesta ahora, con números.»',
    e: 'Escenarios de 10, 50 y 150 personas y cómo lo dejamos en lo mínimo.',
    est: ['Gancho', 'Tabla de escenarios', 'Cómo lo reducimos', 'Pregunta'],
    d: 'Post + imagen con tabla.', x: 'licencias', pre: 'Comprobar precios en la web de Microsoft el mismo día.' },

  // ───────────────────────── Power Pages
  { s: 'Power Pages: portales para tus clientes', r: J, c: 'youtube', f: 'largo', p: PP, t: 'Power Pages con React: el portal del servicio técnico paso a paso',
    tec: 'Power Pages (sitio de código), React, Dataverse, Claude Code', o: 'Power Pages · Portal SAT',
    g: '«Un portal de clientes moderno sobre Power Pages, hecho con código.»',
    e: 'Sitio de código de Power Pages: estructura, roles, permisos de tabla y despliegue.',
    est: ['Resultado', 'Crear el sitio', 'Datos y permisos', 'Desplegar'],
    d: '20 min.', x: 'codeApps', pre: 'Desplegar el Portal SAT en un entorno.' },
  { s: 'Power Pages: portales para tus clientes', r: A, c: 'linkedin', f: 'corto', p: CA, t: 'Tus proveedores confirman los pedidos solos',
    tec: 'Power Apps (Code App), Dataverse', o: 'Code App · Compras (portal de proveedores)',
    g: '«Se acabó llamar al proveedor para saber si ha salido el camión.»',
    e: 'La vista del proveedor: confirmar, proponer cambios y subir documentos.',
    est: ['Vista del proveedor', 'Confirmar', 'Lo que ve la empresa'],
    d: '35 s vertical.', x: 'construidoYo', pre: '—' },
  { s: 'Power Pages: portales para tus clientes', r: J, c: 'linkedin', f: 'post', p: PP, t: 'Power Pages o una web normal: cuándo compensa cada una',
    tec: 'Power Pages, Dataverse', o: 'Power Pages · Portal SAT y DeCA',
    g: '«No todo portal necesita Power Pages. Pero cuando lo necesita, ahorra meses.»',
    e: 'Criterio: usuarios externos, datos en Dataverse, permisos y coste.',
    est: ['Gancho', 'Cuándo sí', 'Cuándo no', 'Pregunta'],
    d: 'Post o carrusel.', x: 'nichoES', pre: 'Revisar el coste de Power Pages por usuario.' },

  // ───────────────────────── Webinars y directos
  { s: 'Webinars y directos', r: J, c: 'linkedin', f: 'webinar', t: 'Digitaliza la mayor parte de tus procesos con Microsoft 365: recorrido por 6 áreas',
    tec: 'Power Apps, Power Automate, Power BI, Copilot Studio', o: 'Todo el catálogo',
    g: '«En 45 minutos, cómo sería tu empresa con ventas, compras, producción, almacén, personal y dirección digitalizados.»',
    e: 'Recorrido por las apps conectadas con demo en directo. Es el mensaje del vídeo de presentación convertido en webinar.',
    est: ['Por qué ahora (5 min)', 'Recorrido por 6 áreas (30 min)', 'Preguntas (10 min)', 'Llamada: revisión de procesos'],
    d: '45 min por Teams, evento de LinkedIn para difundir. Jesús y Alejandro.', x: 'webinar', pre: 'Todas las demos listas; secuencia de promoción de 3 semanas.' },
  { s: 'Webinars y directos', r: J, c: 'linkedin', f: 'webinar', t: 'Agentes de IA para empresas pequeñas y medianas: 3 casos montados en directo',
    tec: 'Copilot Studio, Power Automate, Dataverse', o: 'Agentes nuevos sobre Jornada, Almacén y Portal SAT',
    g: '«Tres agentes de IA útiles para tu empresa, construidos delante de ti.»',
    e: 'Agente de vacaciones, agente del almacén y agente de soporte.',
    est: ['Qué es un agente (5 min)', '3 casos (30 min)', 'Costes reales', 'Preguntas'],
    d: '45 min.', x: 'agenteES', pre: 'Los tres agentes construidos.' },
  { s: 'Webinars y directos', r: A, c: 'linkedin', f: 'webinar', p: PBI, t: 'Power BI para dirección: de tus Excel a un panel en 45 minutos',
    tec: 'Power BI, Claude Code', o: 'Power BI · Catálogo de paneles',
    g: '«Trae tus dudas: montamos un panel de dirección en directo.»',
    e: 'Del Excel al panel, con el diseño de locodea.',
    est: ['El panel terminado', 'Construcción en directo', 'Preguntas'],
    d: '45 min.', x: 'claudePBI', pre: 'Excel de ejemplo inventado.' },
  { s: 'Webinars y directos', r: J, c: 'youtube', f: 'directo', t: 'Construimos una app en directo con Claude Code',
    tec: 'Claude Code, Power Apps (Code App), Dataverse', o: 'Skill de Code Apps',
    g: '«Sin guion y sin cortes: una app de principio a fin en directo.»',
    e: 'Los seguidores proponen un proceso y se construye en directo.',
    est: ['Elegir el proceso con el chat', 'Construir', 'Publicar', 'Preguntas'],
    d: '60–90 min en YouTube. Después, clips.', x: 'claudeCode', pre: 'Probar el directo con StreamYard o similar.' },
  { s: 'Webinars y directos', r: J, c: 'linkedin', f: 'webinar', p: CA, t: 'ISO 9001 sin papel: formación, proveedores y no conformidades en apps',
    tec: 'Power Apps (Code App), Dataverse, Power BI', o: 'Code Apps · Formación y Compras',
    g: '«Prepara tu próxima auditoría con apps, no con carpetas.»',
    e: 'Registro de formación (7.2), evaluación de proveedores (8.4) y no conformidades.',
    est: ['Lo que pide la norma', 'Demo', 'Preguntas'],
    d: '45 min. Invitar a un consultor ISO como coanfitrión.', x: 'webinar', pre: 'Demo de no conformidades.' },
  { s: 'Webinars y directos', r: J, c: 'linkedin', f: 'webinar', t: 'Normativa 2026–2027 para tu empresa: DeCA, cuaderno digital, factura electrónica y VeriFactu',
    tec: 'Power Pages, Power Apps', o: 'DeCA, Surco, Jornada',
    g: '«Todo lo que llega en los próximos meses, explicado en 45 minutos y con soluciones.»',
    e: 'Calendario de obligaciones y la solución para cada una.',
    est: ['Calendario', 'Una obligación y su solución', 'Preguntas'],
    d: '45 min, idealmente con una gestoría.', x: 'normativa', pre: 'Verificar fechas oficiales.' },
  { s: 'Webinars y directos', r: A, c: 'youtube', f: 'directo', t: 'Mándanos una captura de tu app y la rediseñamos en directo',
    tec: 'Power Apps, Figma', o: 'Sistema de diseño locodea.',
    g: '«Tu app de Power Apps, rediseñada en directo.»',
    e: 'Los seguidores mandan capturas (sin datos) y Alejandro las rediseña.',
    est: ['Reglas', '3–4 rediseños', 'Consejos'],
    d: '45 min.', x: 'tipsDiseno', pre: 'Pedir capturas con antelación; sin datos personales.' },
  { s: 'Webinars y directos', r: J, c: 'newsletter', f: 'newsletter', t: 'La carta mensual de locodea.: una app, una automatización y un dato',
    tec: '—', o: 'Todo el banco de ideas',
    g: '«Cada mes, lo que hemos construido y lo que hemos aprendido.»',
    e: 'Newsletter de LinkedIn desde el perfil de Jesús, con lo mejor del mes.',
    est: ['App del mes', 'Automatización del mes', 'Dato del mes', 'Lo que viene'],
    d: 'Mensual.', x: 'nichoES', pre: '—' },
]
